import numpy
from scipy import stats
import pandas
from matplotlib import pyplot
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.graphics.gofplots import qqplot
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.api import OLS

print('read the data')
DF = pandas.read_excel('VIX.xlsx')
V = DF.values[:, 1].astype(float)
N = len(V)
LV = numpy.log(V)
print('number of data points = ', N)
pyplot.plot(V)
pyplot.show()
pyplot.plot(LV)
pyplot.show()
qqplot(V, line = 's')
pyplot.show()
qqplot(LV, line = 's')
pyplot.show()
plot_acf(V)
pyplot.show()
plot_acf(LV)
pyplot.show()
plot_pacf(V)
pyplot.show()
plot_pacf(LV)
pyplot.show()
print('Descriptive Statistics for V')
print(min(V), max(V), numpy.mean(V), numpy.median(V), numpy.std(V), stats.skew(V), stats.kurtosis(V))
print('Descriptive Statistics for LV')
print(min(LV), max(LV), numpy.mean(LV), numpy.median(LV), numpy.std(LV), stats.skew(LV), stats.kurtosis(LV))
print('')
print('')
print('Log AR(1)')
print('')
print('')
RegDF = pandas.DataFrame({'const': 1, 'lag': LV[:-1]})
Reg = OLS(LV[1:], RegDF).fit()
print(Reg.summary())
res = Reg.resid
print('stderr = ', numpy.std(res))
print('Shapiro-Wilk p = ', stats.shapiro(res))
qqplot(res, line = 's')
pyplot.show()
plot_acf(res)
pyplot.show()
plot_acf(abs(res))
pyplot.show()
pyplot.hist(res, bins = 20)
pyplot.show()
print('')
print('')
print('Laplace Fit')
print('')
print('')
scale = numpy.mean(abs(res))
print('Laplace Fit Residuals = ', scale)
QQ = stats.laplace.cdf(numpy.sort(res/scale), 0, 1)
pyplot.plot(numpy.linspace(0, 1, N-1), QQ)
pyplot.plot(numpy.linspace(0, 1, N-1), numpy.linspace(0, 1, N-1))
pyplot.show()
print('')
print('')
print('Asymmetric Laplace Fit')
print('')
print('')
Fit = stats.laplace_asymmetric.fit(res)
print('Estimates: Kappa = ', Fit[0], 'Location = ', Fit[1], 'Scale = ', Fit[2])
print('')
print('')
print('Kolmogorov-Smirnov two-sided test vs symmetric Laplace')
print(stats.kstest(res/scale, stats.laplace.cdf))